language: node_js  

branches:
  only:
    - master

install:
  - yarn install

cache:
  yarn: true
  directories:
     - ./node_modules

# Build stages: https://docs.travis-ci.com/user/build-stages/.
stages:
  - presubmit

jobs:
  include:
    - stage: presubmit
      script: npm run lint
    - stage: presubmit
      script: npm run format:check
