language: node_js  

node_js:
  - node

branches:
  only:
    - master

cache:
  yarn: true
  directories:
     - ./node_modules

matrix:
  fast_finish: true
  include:
    - name: "Check"
      script: npm run tscheck
    - name: "Lint"
      script: npm run lint
    - name: "Format"
      script: npm run format:check
    - name: "Test"
      script: npm run test

after_success:
  - npm run coverage
